# Generated by Django 3.2.23 on 2023-11-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='biography',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
