# Generated by Django 3.2.23 on 2023-11-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatars'),
        ),
    ]
