# Generated by Django 3.2.23 on 2023-11-17 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0012_delete_comment'),
        ('users', '0007_alter_userdata_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('blogentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogentry')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata')),
            ],
        ),
    ]
