# Generated by Django 3.2.23 on 2023-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogentry',
            name='review',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
