# Generated by Django 3.2.23 on 2023-11-13 13:44

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='outstanding',
            field=models.BooleanField(default=False, verbose_name='Destacar'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
