# Generated by Django 3.2.23 on 2023-11-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userdata_avatar'),
        ('blog', '0006_auto_20231115_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userdata'),
        ),
    ]
