# Generated by Django 3.2.23 on 2023-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
