# Generated by Django 3.2.23 on 2023-11-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userdata_avatar'),
        ('blog', '0008_alter_blogentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata'),
        ),
    ]
