# Generated by Django 3.2.23 on 2023-11-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userdata_avatar'),
        ('blog', '0009_alter_blogentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='user',
            new_name='userdata',
        ),
        migrations.AddField(
            model_name='comment',
            name='blogentry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.blogentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='userdata',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.userdata'),
            preserve_default=False,
        ),
    ]
